### ISSUE TITLE
Google Camera crash

### ISSUE THREAD

**Issue by Genetik57** [AOSP-Krypton/device_oneplus_sm8150-common#17]
Hi,

I have downloaded the latest version of Google Camera on the Play Store and impossible to use it.

When I launch it I have this error

Logs here : https://www.toptal.com/developers/hastebin/alopabobuv

I have a OnePlus 7 with the latest version available on xda

Can you fix this?

Best regards

**Comment by Codecity001** [comment]
Why would u use a Google Camera from Playstore

**Comment by Genetik57** [comment]
Because I like Google Camera

**Comment by Codecity001** [comment]
> Because I like Google Camera
U can just use a GCAM which is compatible with OP7
